# Generated by Django 3.0.1 on 2020-01-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(default='', max_length=5)),
                ('car_count', models.IntegerField(default=0)),
            ],
        ),
    ]
