# Generated by Django 2.1.5 on 2019-08-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slot',
            name='index',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zone.Index'),
        ),
        migrations.AddField(
            model_name='slot',
            name='zone',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zone.Zone'),
        ),
        migrations.AddField(
            model_name='zone',
            name='name',
            field=models.CharField(default='', max_length=3),
        ),
    ]
