# Generated by Django 3.0.1 on 2020-02-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_carslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarSlot',
        ),
        migrations.DeleteModel(
            name='Index',
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='index_number',
            new_name='car_count',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='empty',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='zone_name',
        ),
        migrations.AddField(
            model_name='slot',
            name='slot_name',
            field=models.CharField(default='', max_length=5),
        ),
    ]
