# Generated by Django 2.1.5 on 2019-08-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0002_auto_20190829_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='empty',
            field=models.BooleanField(default=True),
        ),
    ]
