# Generated by Django 2.1.5 on 2019-08-30 13:14

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('entry_time', models.DateTimeField(default=datetime.datetime(2019, 8, 30, 13, 14, 13, 729771))),
            ],
        ),
    ]
