# Generated by Django 2.1.5 on 2019-09-16 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylog',
            name='car_id',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='entrylog',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 16, 10, 40, 8, 972679)),
        ),
    ]
