# Generated by Django 3.0.1 on 2020-01-23 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_log', '0002_auto_20190916_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrylog',
            name='entry_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 23, 5, 14, 34, 59075)),
        ),
    ]
